on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      #       - name: Upload from public_html via FTP
      #         uses: airvzxf/ftp-deployment-action@latest
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "/home3/arbrefos/quiz.arbreefos.com"
