on:
  push:
    branches: [ master ]
name: 🚀 Deploy website on push

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: '${{ secrets.FTP_USERNAME }}'
          server: '${{ secrets.FTP_SERVER }}'
          ssh_private_key: ${{ secrets.SFTP_ACCESS_TOKEN }}
          local_path: './'
          remote_path: '/home3/arbrefos/quiz.arbreefos.com'
          args: '-o ConnectTimeout=5'
          

# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v2
#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           protocol: ftps
#           port:  21
#           local-dir: "./"
#           server-dir: "./quiz.arbreefos.com/"
